export const FLIGHT_LOADING = "FLIGHT_LOADING";
export const FLIGHTS_FOR_AIRLINE_LOADING = "FLIGHTS_FOR_AIRLINE_LOADING";
export const SEARCH_FLIGHTS = 'SEARCH_FLIGHTS';
export const FILTER_FLIGHTS = 'FILTER_FLIGHTS';
export const SELECT_FLIGHT_FOR_BOOKING = 'SELECT_FLIGHT_FOR_BOOKINGING_FLIGHT';
