export const LOAD_BITCOIN_DOLLAR_EXCHAGE = "LOAD_BITCOIN_DOLLAR_EXCHAGE";
export const LOAD_TICKETS_FOR_ENTERED_AIRLINE =
  "LOAD_TICKETS_FOR_ENTERED_AIRLINE";
  export const ADD_NEW_TIME_VALUE = 'ADD_NEW_TIME_VALUE';
