export const LOADING_MY_REQUESTS = 'LOADING_MY_REQUESTS'
export const LOADING_REQUESTS_FOR_ME = 'LOADING_REQUESTS_FOR_ME'
export const LOADING_FRIENDS = 'LOADING_FRIENDS'
export const SEARCH_FRIENDS = 'SEARCH_FRIENDS'